# Generated by Django 5.2.5 on 2026-08-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_main_and_vendor_permission_history'),
        ('vendors', '0008_organizationunit_organizationclientaccess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='vendors.organizationunit'),
        ),
    ]
