# Generated by Django 5.2.5 on 2026-08-10 16:07

import django.core.validators
from django.db import migrations, models

from accounts.function_catalog import FUNCTION_CATALOG


NEW_CODES = {
    "projects.filter.buyer",
    "projects.filter.survey_type",
    "studies.filter.client",
    "studies.filter.buyer",
    "studies.filter.project",
}


def seed_new_component_permissions(apps, schema_editor):
    AccessFunction = apps.get_model("accounts", "AccessFunction")
    Role = apps.get_model("accounts", "Role")
    RoleFunctionPermission = apps.get_model("accounts", "RoleFunctionPermission")
    for code, name, module, description, default_roles in FUNCTION_CATALOG:
        if code not in NEW_CODES:
            continue
        function, _created = AccessFunction.objects.update_or_create(
            code=code,
            defaults={"name": name, "module": module, "description": description, "is_active": True},
        )
        for role in Role.objects.filter(slug__in=default_roles, is_active=True):
            RoleFunctionPermission.objects.get_or_create(
                role=role,
                function=function,
                defaults={"allowed": True},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_split_summary_card_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='cpi_visibility_percent',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Percentage of CPI visible to employee accounts assigned this role.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.RunPython(seed_new_component_permissions, migrations.RunPython.noop),
    ]
