worker_processes 1;
pid /home/alessarsolutions.in/tmp/alessar-frontend-nginx.pid;
error_log /home/alessarsolutions.in/app_logs/alessar-frontend-error.log warn;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /home/alessarsolutions.in/app_logs/alessar-frontend-access.log;
    sendfile on;
    keepalive_timeout 65;
    client_body_temp_path /home/alessarsolutions.in/tmp/client_body;
    proxy_temp_path /home/alessarsolutions.in/tmp/proxy;
    fastcgi_temp_path /home/alessarsolutions.in/tmp/fastcgi;
    uwsgi_temp_path /home/alessarsolutions.in/tmp/uwsgi;
    scgi_temp_path /home/alessarsolutions.in/tmp/scgi;

    server {
        listen 127.0.0.1:8092;
        server_name _;
        root /home/alessarsolutions.in/public_html;
        index index.html;

        location /assets/ {
            try_files $uri =404;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
