# Generated by Django 5.2.5 on 2026-08-13 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescreener_vault', '0003_prescreenersubmission_usage_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CintRespondentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_email', models.TextField(editable=False)),
                ('email_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('assigned_uid', models.CharField(blank=True, editable=False, max_length=19, null=True, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('disabled', 'Disabled')], db_index=True, default='available', max_length=12)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('first_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['status', 'assigned_at'], name='vault_cint_email_pool_idx')],
            },
        ),
        migrations.CreateModel(
            name='CintRespondentEmailUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=10, unique=True)),
                ('used_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_uses', to='prescreener_vault.cintrespondentemail')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
