# Generated by Django 5.2.5 on 2026-08-18 10:09

from django.db import migrations, models


def normalize_reuse_buckets(apps, schema_editor):
    submission = apps.get_model("prescreener_vault", "PrescreenerSubmission")
    rows = submission.objects.using(schema_editor.connection.alias)
    rows.update(respondent_age_group="")
    for lower, upper in (
        (13, 17), (18, 24), (25, 29), (30, 34),
        (35, 39), (40, 44), (45, 49), (50, 54),
    ):
        rows.filter(respondent_age__gte=lower, respondent_age__lte=upper).update(
            respondent_age_group=f"{lower}-{upper}"
        )
    for value in ("male", "m", "man"):
        rows.filter(respondent_gender__iexact=value).update(respondent_gender="male")
    for value in ("female", "f", "woman"):
        rows.filter(respondent_gender__iexact=value).update(respondent_gender="female")


class Migration(migrations.Migration):

    dependencies = [
        ('prescreener_vault', '0004_cintrespondentemail_cintrespondentemailuse'),
    ]

    operations = [
        migrations.RunPython(normalize_reuse_buckets, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='prescreenersubmission',
            index=models.Index(fields=['country_code', 'respondent_age_group', 'respondent_gender', 'usage_count', 'submitted_at'], name='vault_reuse_queue_idx'),
        ),
    ]
