# Generated by Django 5.2.5 on 2026-08-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescreener_vault', '0006_client_scoped_reuse_pool'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prescreenersubmission',
            index=models.Index(fields=['source_client_code', 'country_code', 'respondent_gender', 'respondent_age'], name='vault_reuse_age_idx'),
        ),
    ]
