# Generated by Django 5.2.16 on 2026-08-04 18:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client', models.CharField(db_index=True, max_length=80)),
                ('survey_id', models.CharField(db_index=True, max_length=160)),
                ('transaction_id', models.CharField(max_length=64, unique=True)),
                ('respondent_id', models.CharField(max_length=64, unique=True)),
                ('entry_url', models.URLField(max_length=2000)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('handed_off', 'Sent to survey'), ('complete', 'Complete'), ('terminate', 'Terminate'), ('quota_full', 'Quota full'), ('security_terminate', 'Security terminate')], db_index=True, default='initiated', max_length=32)),
                ('prescreener_answers', models.JSONField(blank=True, default=dict)),
                ('supplier_status_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('handed_off_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['client', 'survey_id', '-created_at'], name='surveys_sur_client_7b6aac_idx')],
            },
        ),
    ]
