# Generated by Django 5.2.5 on 2026-08-06 10:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalIdSequence',
            fields=[
                ('year_month', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'local ID sequence',
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=12)),
                ('fetched_full', models.PositiveIntegerField(default=0)),
                ('fetched_paged', models.PositiveIntegerField(default=0)),
                ('unique_surveys', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('unchanged', models.PositiveIntegerField(default=0)),
                ('closed', models.PositiveIntegerField(default=0)),
                ('detail_failures', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(db_index=True, editable=False, max_length=14, unique=True)),
                ('source_id', models.PositiveBigIntegerField(db_index=True, help_text='InnovateMR surveyId', unique=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('live', 'Live'), ('closed', 'Closed')], db_index=True, default='live', max_length=12)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('completes', models.PositiveIntegerField(default=0)),
                ('remaining', models.PositiveIntegerField(default=0)),
                ('starts', models.PositiveIntegerField(default=0)),
                ('cpi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('loi', models.PositiveIntegerField(blank=True, null=True)),
                ('incidence_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=120)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=8)),
                ('language', models.CharField(blank=True, max_length=80)),
                ('language_code', models.CharField(blank=True, max_length=8)),
                ('group_type', models.CharField(blank=True, max_length=80)),
                ('device_type', models.CharField(blank=True, max_length=80)),
                ('entry_link', models.URLField(blank=True, max_length=2000)),
                ('test_entry_link', models.URLField(blank=True, max_length=2000)),
                ('job_category', models.CharField(blank=True, max_length=180)),
                ('has_quota', models.BooleanField(default=False)),
                ('is_pii_required', models.BooleanField(default=False)),
                ('is_recontact', models.BooleanField(default=False)),
                ('source_created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_modified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('detail_synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-source_modified_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'country_code'], name='surveys_sur_status_be4b03_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=120)),
                ('quota_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('remaining', models.PositiveIntegerField(default=0)),
                ('completes', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('targeting', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='surveys.survey')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('survey', 'source_key'), name='unique_survey_quota')],
            },
        ),
        migrations.CreateModel(
            name='TargetingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.BigIntegerField()),
                ('key', models.CharField(blank=True, max_length=180)),
                ('text', models.TextField(blank=True)),
                ('question_type', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('options', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeting_questions', to='surveys.survey')),
            ],
            options={
                'ordering': ['question_id'],
                'constraints': [models.UniqueConstraint(fields=('survey', 'question_id'), name='unique_survey_question')],
            },
        ),
    ]
