# Generated by Django 5.2.5 on 2026-08-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLease',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
