# Generated by Django 5.2.5 on 2026-08-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_synclease'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='company_name',
            field=models.CharField(db_index=True, default='InnovateMR', max_length=160),
        ),
    ]
