# Generated by Django 5.2.5 on 2026-08-07 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='quota_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='targeting_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SurveyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(db_index=True, max_length=10, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=160)),
                ('supplier_code', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('redirected', 'Redirected to survey'), ('1', 'Completed'), ('2', 'Terminated'), ('3', 'Over quota'), ('4', 'Quality terminated')], db_index=True, default='initiated', max_length=20)),
                ('initiated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('redirected_at', models.DateTimeField(blank=True, null=True)),
                ('callback_at', models.DateTimeField(blank=True, null=True)),
                ('last_callback_at', models.DateTimeField(blank=True, null=True)),
                ('loi_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('initiation_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('callback_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('outbound_url', models.URLField(blank=True, max_length=3000)),
                ('callback_count', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='True only after a trusted S2S notification/hash verification.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='surveys.survey')),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['survey', 'user_id', '-initiated_at'], name='surveys_sur_survey__5c9053_idx')],
            },
        ),
    ]
