# Generated by Django 5.2.5 on 2026-08-08 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_surveyattempt_upstream_reconciliation'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='vendors.client'),
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='vendors.client'),
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='client_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='vendors.vendorclientallocation'),
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='cpi_currency_snapshot',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='cpi_cut_percent_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='payable_cpi_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='source_cpi_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_owned_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
