# Generated by Django 5.2.5 on 2026-08-08 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_survey_client_surveyattempt_client_and_more'),
        ('vendors', '0002_vendorsurveyallocation_allocationreservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattempt',
            name='survey_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='vendors.vendorsurveyallocation'),
        ),
    ]
