# Generated by Django 5.2.5 on 2026-08-10 16:07

from decimal import Decimal, InvalidOperation

from django.db import migrations, models


def _survey_type(value):
    text = str(value or "").strip()
    normalized = "".join(character for character in text.upper() if character.isalnum())
    if normalized in {"B2B", "BUSINESS", "BUSINESSTOBUSINESS"}:
        return "B2B"
    if normalized in {"B2C", "CONSUMER", "BUSINESSTOCONSUMER"}:
        return "B2C"
    return text[:20]


def _decimal(value):
    try:
        cleaned = str(value).replace("$", "").replace(",", "").strip()
        parsed = Decimal(cleaned)
        return parsed if parsed >= 0 else None
    except (InvalidOperation, TypeError, ValueError):
        return None


def _provider_cpi(payload):
    if isinstance(payload, dict):
        for key in ("CPI", "cpi", "sourceCpi", "source_cpi"):
            parsed = _decimal(payload.get(key))
            if parsed is not None:
                return parsed
        for key in ("transaction", "result", "data", "rows", "items"):
            parsed = _provider_cpi(payload.get(key))
            if parsed is not None:
                return parsed
    elif isinstance(payload, list):
        for item in payload:
            parsed = _provider_cpi(item)
            if parsed is not None:
                return parsed
    return None


def backfill_buyer_type_and_revenue(apps, schema_editor):
    Survey = apps.get_model("surveys", "Survey")
    SurveyAttempt = apps.get_model("surveys", "SurveyAttempt")

    survey_updates = []
    for survey in Survey.objects.all().iterator(chunk_size=1000):
        raw = survey.raw_data if isinstance(survey.raw_data, dict) else {}
        survey.buyer_id = str(raw.get("BuyerId") or raw.get("buyerId") or raw.get("buyer_id") or "").strip()[:160]
        survey.survey_type = _survey_type(
            survey.group_type or raw.get("groupType") or raw.get("surveyType") or raw.get("category")
        )
        survey_updates.append(survey)
        if len(survey_updates) >= 1000:
            Survey.objects.bulk_update(survey_updates, ["buyer_id", "survey_type"], batch_size=1000)
            survey_updates = []
    if survey_updates:
        Survey.objects.bulk_update(survey_updates, ["buyer_id", "survey_type"], batch_size=1000)

    survey_cpi = dict(Survey.objects.values_list("id", "cpi"))
    attempt_updates = []
    for attempt in SurveyAttempt.objects.all().iterator(chunk_size=1000):
        if attempt.source_cpi_snapshot is not None:
            attempt.cpi_snapshot_source = "captured"
        else:
            recovered = _provider_cpi(attempt.upstream_transaction_data)
            if recovered is not None:
                attempt.source_cpi_snapshot = recovered
                attempt.cpi_snapshot_source = "provider_transaction"
            elif attempt.payable_cpi_snapshot is not None:
                attempt.source_cpi_snapshot = attempt.payable_cpi_snapshot
                attempt.cpi_snapshot_source = "payable_snapshot"
            elif survey_cpi.get(attempt.survey_id) is not None:
                attempt.source_cpi_snapshot = survey_cpi[attempt.survey_id]
                attempt.cpi_snapshot_source = "legacy_survey"
            else:
                attempt.cpi_snapshot_source = "unavailable"
        if attempt.source_cpi_snapshot is not None and not attempt.cpi_currency_snapshot:
            attempt.cpi_currency_snapshot = "USD"
        attempt_updates.append(attempt)
        if len(attempt_updates) >= 1000:
            SurveyAttempt.objects.bulk_update(
                attempt_updates,
                ["source_cpi_snapshot", "cpi_snapshot_source", "cpi_currency_snapshot"],
                batch_size=1000,
            )
            attempt_updates = []
    if attempt_updates:
        SurveyAttempt.objects.bulk_update(
            attempt_updates,
            ["source_cpi_snapshot", "cpi_snapshot_source", "cpi_currency_snapshot"],
            batch_size=1000,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_survey_string_source_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='buyer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Provider buyer/sub-client identifier.', max_length=160),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized survey audience type, such as B2B or B2C.', max_length=20),
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='cpi_snapshot_source',
            field=models.CharField(blank=True, help_text='How the immutable source CPI snapshot was captured or recovered.', max_length=24),
        ),
        migrations.RunPython(backfill_buyer_type_and_revenue, migrations.RunPython.noop),
    ]
