# Generated by Django 5.2.5 on 2026-08-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_canonical_provider_mappings'),
        ('vendors', '0013_cint_country_language_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CintWebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('payload_sha256', models.CharField(db_index=True, max_length=64)),
                ('signature_timestamp', models.PositiveBigIntegerField(blank=True, null=True)),
                ('signature_key_id', models.CharField(blank=True, max_length=80)),
                ('signature_header', models.TextField(blank=True)),
                ('payload', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='received', max_length=16)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('closed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cint_webhook_deliveries', to='vendors.clientintegration')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['integration', 'status', 'received_at'], name='surveys_cin_integra_269aec_idx')],
            },
        ),
    ]
