# Generated by Django 5.2.5 on 2026-08-18 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_hydrate_cint_webhook_question_metadata'),
        ('vendors', '0019_clientintegration_profile_reuse_age_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattempt',
            name='provider_profile_uid',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Reusable UID actually sent to the provider; blank means prescreener_uid was used.', max_length=19),
        ),
        migrations.CreateModel(
            name='ProfileReuseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_uid', models.CharField(db_index=True, max_length=19)),
                ('reused_uid', models.CharField(db_index=True, max_length=19)),
                ('source_registered_at', models.DateTimeField()),
                ('source_usage_number', models.PositiveIntegerField()),
                ('country_code', models.CharField(db_index=True, max_length=8)),
                ('age_group', models.CharField(db_index=True, max_length=20)),
                ('gender', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile_reuse_event', to='surveys.surveyattempt')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_reuse_events', to='vendors.clientintegration')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['integration', 'created_at'], name='surveys_pro_integra_a4adaf_idx'), models.Index(fields=['integration', 'country_code', 'age_group', 'gender'], name='surveys_pro_integra_ab5d6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileReuseMonthlyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('baseline_attempts', models.PositiveIntegerField(default=0)),
                ('target_reuses', models.PositiveIntegerField(default=0)),
                ('allocated_reuses', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_reuse_months', to='vendors.clientintegration')),
            ],
            options={
                'indexes': [models.Index(fields=['integration', 'period_start'], name='surveys_pro_integra_b0ea0f_idx')],
                'constraints': [models.UniqueConstraint(fields=('integration', 'period_start'), name='unique_profile_reuse_month')],
            },
        ),
    ]
