# Generated by Django 5.2.5 on 2026-08-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_profile_reuse_two_pool_counters'),
        ('vendors', '0021_organizationclientaccess_max_cpi_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['client', 'cpi'], name='surveys_sur_client__c4463b_idx'),
        ),
    ]
