# Generated by Django 5.2.5 on 2026-08-20 07:37

import django.db.models.deletion
from django.db import migrations, models


def populate_project_locks(apps, schema_editor):
    Event = apps.get_model('surveys', 'ProfileReuseEvent')
    ProjectUsage = apps.get_model('surveys', 'ProfileReuseProjectUsage')
    Attempt = apps.get_model('surveys', 'SurveyAttempt')
    alias = schema_editor.connection.alias
    events = Event.objects.using(alias).select_related('attempt').only(
        'pk', 'integration_id', 'reused_uid', 'attempt_id', 'attempt__survey_id'
    ).order_by('created_at', 'pk')
    for event in events.iterator(chunk_size=1000):
        survey_id = event.attempt.survey_id
        Event.objects.using(alias).filter(pk=event.pk).update(survey_id=survey_id)
        ProjectUsage.objects.using(alias).get_or_create(
            integration_id=event.integration_id,
            survey_id=survey_id,
            reused_uid=event.reused_uid,
            defaults={'first_attempt_id': event.attempt_id},
        )

    # Registration itself counts as the UID's first use on a project.  Seed
    # those locks too so profiles captured before this migration cannot later
    # return to their original survey.
    for field_name in ('prescreener_uid', 'provider_profile_uid'):
        attempts = Attempt.objects.using(alias).exclude(**{field_name: ''}).select_related(
            'survey'
        ).only('pk', 'survey_id', 'survey__integration_id', field_name)
        for attempt in attempts.iterator(chunk_size=1000):
            integration_id = attempt.survey.integration_id
            reused_uid = getattr(attempt, field_name)
            if not integration_id or not reused_uid:
                continue
            ProjectUsage.objects.using(alias).get_or_create(
                integration_id=integration_id,
                survey_id=attempt.survey_id,
                reused_uid=reused_uid,
                defaults={'first_attempt_id': attempt.pk},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_survey_surveys_sur_client__c4463b_idx'),
        ('vendors', '0023_clientintegration_profile_reuse_first_delay_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileReuseProjectUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reused_uid', models.CharField(max_length=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileReuseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reused_uid', models.CharField(max_length=19)),
                ('last_reused_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total_reuses', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='profilereuseevent',
            name='survey',
            field=models.ForeignKey(help_text='Denormalized project identity used for permanent same-project exclusion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_reuse_events', to='surveys.survey'),
        ),
        migrations.AddIndex(
            model_name='profilereuseevent',
            index=models.Index(fields=['integration', 'reused_uid', 'created_at'], name='surveys_pro_integra_8fb692_idx'),
        ),
        migrations.AddField(
            model_name='profilereuseprojectusage',
            name='first_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_reuse_project_locks', to='surveys.surveyattempt'),
        ),
        migrations.AddField(
            model_name='profilereuseprojectusage',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_reuse_project_usages', to='vendors.clientintegration'),
        ),
        migrations.AddField(
            model_name='profilereuseprojectusage',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_reuse_project_usages', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='profilereusestate',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_reuse_states', to='vendors.clientintegration'),
        ),
        migrations.RunPython(populate_project_locks, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profilereuseevent',
            name='survey',
            field=models.ForeignKey(help_text='Denormalized project identity used for permanent same-project exclusion.', on_delete=django.db.models.deletion.PROTECT, related_name='profile_reuse_events', to='surveys.survey'),
        ),
        migrations.AddIndex(
            model_name='profilereuseprojectusage',
            index=models.Index(fields=['integration', 'survey'], name='surveys_pro_integra_a7b4f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='profilereuseprojectusage',
            constraint=models.UniqueConstraint(fields=('integration', 'survey', 'reused_uid'), name='unique_profile_uid_per_project'),
        ),
        migrations.AddIndex(
            model_name='profilereusestate',
            index=models.Index(fields=['integration', 'last_reused_at'], name='surveys_pro_integra_2311d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='profilereusestate',
            constraint=models.UniqueConstraint(fields=('integration', 'reused_uid'), name='unique_profile_reuse_state'),
        ),
    ]
