# Generated by Django 5.2.17 on 2026-08-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_postgresql_hot_path_indexes'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='surveyattempt',
                    name='attempt_reconcile_idx',
                ),
            ],
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='supplier_respondent_id',
            field=models.CharField(blank=True, db_index=True, help_text="External supplier's respondent identifier, echoed only to that supplier's redirect.", max_length=160),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='surveyattempt',
                    index=models.Index(
                        models.OrderBy(models.F('upstream_checked_at'), nulls_first=True),
                        models.OrderBy(models.F('initiated_at'), descending=True),
                        name='attempt_reconcile_idx',
                        condition=models.Q(status='redirected', callback_at__isnull=True),
                    ),
                ),
            ],
        ),
    ]
