# Generated by Django 5.2.17 on 2026-08-20 20:58

import django.db.models.deletion
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_surveyattempt_supplier_respondent_id'),
        ('vendors', '0025_alter_vendorapikey_client_allocations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # PostgreSQL owns this ordered index through migration 0026's guarded
        # DDL. Keep it out of SQLite table rebuilds while fields are added;
        # SQLite does not support NULLS FIRST in index definitions.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='survey',
                    name='survey_sync_detail_idx',
                ),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='inventory_source',
            field=models.CharField(choices=[('api', 'API / synchronized'), ('manual', 'Manual link')], db_index=True, default='api', max_length=12),
        ),
        migrations.AddField(
            model_name='survey',
            name='manual_rid_parameter',
            field=models.CharField(blank=True, help_text='Query-string parameter that receives the RM Wins respondent RID.', max_length=64, validators=[django.core.validators.RegexValidator(message='Use 1-64 letters, numbers, dots, dashes or underscores; start with a letter.', regex='^[A-Za-z][A-Za-z0-9_.-]{0,63}$')]),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_source', 'manual')), fields=('client', 'source_key'), name='unique_manual_client_survey_key'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='survey',
                    index=models.Index(
                        models.F('integration'),
                        models.F('status'),
                        models.OrderBy(models.F('detail_synced_at'), nulls_first=True),
                        models.OrderBy(models.F('source_modified_at'), descending=True, nulls_last=True),
                        name='survey_sync_detail_idx',
                    ),
                ),
            ],
        ),
    ]
