# Generated by Django 5.2.5 on 2026-08-08 04:28

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('provider_code', models.SlugField(default='innovatemr', max_length=80)),
                ('company_name_match', models.CharField(blank=True, help_text='Current survey company label used while legacy inventory is mapped to this client.', max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VendorCommercialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_cpi_cut_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendor_commercial_profiles', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_commercial_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vendor__first_name', 'vendor__username'],
            },
        ),
        migrations.CreateModel(
            name='ClientIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider_code', models.SlugField(default='innovatemr', max_length=80)),
                ('base_url', models.URLField(max_length=500)),
                ('credential_env_key', models.CharField(blank=True, help_text='Environment-variable name containing the token. Secret values are never stored here.', max_length=120)),
                ('scheduled_sync_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrations', to='vendors.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('client', 'name'), name='unique_client_integration_name')],
            },
        ),
        migrations.CreateModel(
            name='VendorClientAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_limit', models.PositiveBigIntegerField(default=0)),
                ('reserved_quantity', models.PositiveBigIntegerField(default=0, editable=False)),
                ('consumed_quantity', models.PositiveBigIntegerField(default=0, editable=False)),
                ('cpi_cut_override_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Optional client-specific cut. Blank uses the vendor commercial default.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_allocations', to='vendors.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendor_client_allocations', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client__name', 'vendor__first_name', 'vendor__username'],
                'indexes': [models.Index(fields=['vendor', 'is_active'], name='vendors_ven_vendor__b813cb_idx'), models.Index(fields=['client', 'is_active'], name='vendors_ven_client__96d2d7_idx')],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'client'), name='unique_vendor_client_allocation'), models.CheckConstraint(condition=models.Q(('consumed_quantity__lte', models.F('quantity_limit'))), name='client_consumed_not_above_limit'), models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', django.db.models.expressions.CombinedExpression(models.F('quantity_limit'), '-', models.F('consumed_quantity')))), name='client_reserved_within_remaining')],
            },
        ),
    ]
