# Generated by Django 5.2.5 on 2026-08-08 04:29

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_survey_client_surveyattempt_client_and_more'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSurveyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_limit', models.PositiveBigIntegerField(default=0)),
                ('reserved_quantity', models.PositiveBigIntegerField(default=0, editable=False)),
                ('consumed_quantity', models.PositiveBigIntegerField(default=0, editable=False)),
                ('cpi_cut_override_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Optional survey-specific cut. Blank uses the client/vendor policy.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_allocations', to='vendors.vendorclientallocation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendor_survey_allocations', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_allocations', to='surveys.survey')),
            ],
            options={
                'ordering': ['survey__source_id', 'client_allocation__vendor__username'],
            },
        ),
        migrations.CreateModel(
            name='AllocationReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('consumed', 'Consumed'), ('released', 'Released'), ('expired', 'Expired')], db_index=True, default='reserved', max_length=12)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_reservation', to='surveys.surveyattempt')),
                ('client_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='vendors.vendorclientallocation')),
                ('survey_allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='vendors.vendorsurveyallocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendorsurveyallocation',
            index=models.Index(fields=['survey', 'is_active'], name='vendors_ven_survey__2103f4_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorsurveyallocation',
            index=models.Index(fields=['client_allocation', 'is_active'], name='vendors_ven_client__381abe_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorsurveyallocation',
            constraint=models.UniqueConstraint(fields=('client_allocation', 'survey'), name='unique_vendor_survey_allocation'),
        ),
        migrations.AddConstraint(
            model_name='vendorsurveyallocation',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_quantity__lte', models.F('quantity_limit'))), name='survey_consumed_not_above_limit'),
        ),
        migrations.AddConstraint(
            model_name='vendorsurveyallocation',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', django.db.models.expressions.CombinedExpression(models.F('quantity_limit'), '-', models.F('consumed_quantity')))), name='survey_reserved_within_remaining'),
        ),
        migrations.AddIndex(
            model_name='allocationreservation',
            index=models.Index(fields=['status', 'expires_at'], name='vendors_all_status_b4a453_idx'),
        ),
    ]
