# Generated by Django 5.2.5 on 2026-08-08 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_seed_innovatemr_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationreservation',
            name='survey_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='vendors.vendorsurveyallocation'),
        ),
    ]
