# Generated by Django 5.2.5 on 2026-08-08 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_vendor_commercial_profiles(apps, schema_editor):
    EmployeeProfile = apps.get_model("accounts", "EmployeeProfile")
    VendorCommercialProfile = apps.get_model("vendors", "VendorCommercialProfile")
    for profile in EmployeeProfile.objects.filter(account_type__in=["internal_vendor", "external_vendor"]):
        commercial, _ = VendorCommercialProfile.objects.get_or_create(
            vendor_id=profile.user_id,
            defaults={"default_cpi_cut_percent": 0, "currency": "USD", "delivery_mode": "panel"},
        )
        if profile.account_type == "internal_vendor":
            changes = []
            if commercial.default_cpi_cut_percent:
                commercial.default_cpi_cut_percent = 0
                changes.append("default_cpi_cut_percent")
            if commercial.delivery_mode != "panel":
                commercial.delivery_mode = "panel"
                changes.append("delivery_mode")
            if changes:
                commercial.save(update_fields=changes)


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_allocationreservation_survey_allocation'),
        ('accounts', '0008_seed_vendor_account_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcommercialprofile',
            name='delivery_mode',
            field=models.CharField(choices=[('panel', 'Panel only'), ('api', 'API only'), ('both', 'Panel and API')], db_index=True, default='panel', help_text='Controls whether an external vendor can sign in to the panel, use API keys, or both.', max_length=8),
        ),
        migrations.CreateModel(
            name='VendorAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('prefix', models.CharField(db_index=True, max_length=16)),
                ('last_four', models.CharField(max_length=4)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendor_api_keys', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'is_active'], name='vendors_ven_vendor__2b7644_idx')],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'name'), name='unique_vendor_api_key_name')],
            },
        ),
        migrations.RunPython(ensure_vendor_commercial_profiles, migrations.RunPython.noop),
    ]
