# Generated by Django 5.2.5 on 2026-08-09 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_clientintegration_api_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('branch', 'Branch'), ('sub_branch', 'Sub-branch'), ('shift', 'Shift')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organization_units', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='vendors.organizationunit')),
                ('workspace_owner', models.ForeignKey(help_text='The super-admin workspace or internal vendor that owns this hierarchy.', on_delete=django.db.models.deletion.PROTECT, related_name='organization_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['workspace_owner_id', 'unit_type', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationClientAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_access_rules', to='vendors.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organization_client_access_rules', to=settings.AUTH_USER_MODEL)),
                ('organization_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_access_rules', to='vendors.organizationunit')),
            ],
            options={
                'ordering': ['organization_unit__workspace_owner_id', 'organization_unit__name', 'client__name'],
            },
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['workspace_owner', 'unit_type', 'is_active'], name='vendors_org_workspa_71bcf3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['parent', 'is_active'], name='vendors_org_parent__6647cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationunit',
            constraint=models.UniqueConstraint(fields=('workspace_owner', 'parent', 'unit_type', 'code'), name='unique_organization_unit_code_in_parent'),
        ),
        migrations.AddIndex(
            model_name='organizationclientaccess',
            index=models.Index(fields=['organization_unit', 'is_active'], name='vendors_org_organiz_d28765_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationclientaccess',
            index=models.Index(fields=['client', 'is_active'], name='vendors_org_client__fdcb4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationclientaccess',
            constraint=models.UniqueConstraint(fields=('organization_unit', 'client'), name='unique_client_access_per_organization_unit'),
        ),
    ]
