# Generated by Django 5.2.5 on 2026-08-18 10:09

import django.core.validators
import vendors.models
from decimal import Decimal
from django.db import migrations, models


def migrate_legacy_cint_reuse_config(apps, schema_editor):
    integration_model = apps.get_model("vendors", "ClientIntegration")
    for integration in integration_model.objects.filter(provider_code="cint").iterator():
        config = integration.config or {}
        if not any(key in config for key in ("profile_reuse_enabled", "profile_reuse_percentage")):
            continue
        integration.profile_reuse_enabled = config.get("profile_reuse_enabled") is True
        try:
            integration.profile_reuse_monthly_percentage = max(
                0, min(100, int(config.get("profile_reuse_percentage", 30)))
            )
        except (TypeError, ValueError):
            integration.profile_reuse_monthly_percentage = 30
        integration.save(update_fields=[
            "profile_reuse_enabled", "profile_reuse_monthly_percentage",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_vendorapikey_client_allocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintegration',
            name='profile_reuse_age_groups',
            field=models.JSONField(blank=True, default=vendors.models.default_profile_reuse_age_groups),
        ),
        migrations.AddField(
            model_name='clientintegration',
            name='profile_reuse_country_codes',
            field=models.JSONField(blank=True, default=list, help_text='Allowed ISO country codes. Empty means every country served by this integration.'),
        ),
        migrations.AddField(
            model_name='clientintegration',
            name='profile_reuse_eligible_after_days',
            field=models.PositiveSmallIntegerField(default=60, help_text='Minimum age of a registered UID before it enters the reuse queue.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(730)]),
        ),
        migrations.AddField(
            model_name='clientintegration',
            name='profile_reuse_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Allow this client to receive an eligible previously registered profile UID.'),
        ),
        migrations.AddField(
            model_name='clientintegration',
            name='profile_reuse_genders',
            field=models.JSONField(blank=True, default=vendors.models.default_profile_reuse_genders),
        ),
        migrations.AddField(
            model_name='clientintegration',
            name='profile_reuse_monthly_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text="Percentage of the previous calendar month's attempts available as this month's reuse budget.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.RunPython(migrate_legacy_cint_reuse_config, migrations.RunPython.noop),
    ]
