# Generated by Django 5.2.5 on 2026-08-19 12:52

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_clientintegration_repeat_reuse_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationclientaccess',
            name='max_cpi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional source-CPI ceiling inherited by child units.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='organizationclientaccess',
            name='min_cpi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional source-CPI floor inherited by child units.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='vendorclientallocation',
            name='max_cpi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional source-CPI ceiling for this supplier/client grant.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='vendorclientallocation',
            name='min_cpi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional source-CPI floor for this supplier/client grant.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='organizationclientaccess',
            constraint=models.CheckConstraint(condition=models.Q(('min_cpi__isnull', True), ('max_cpi__isnull', True), ('min_cpi__lte', models.F('max_cpi')), _connector='OR'), name='organization_client_cpi_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='vendorclientallocation',
            constraint=models.CheckConstraint(condition=models.Q(('min_cpi__isnull', True), ('max_cpi__isnull', True), ('min_cpi__lte', models.F('max_cpi')), _connector='OR'), name='vendor_client_cpi_range_valid'),
        ),
    ]
