# Generated by Django 5.2.5 on 2026-08-19 14:20

from django.db import migrations, models


def preserve_existing_child_cpi_overrides(apps, schema_editor):
    OrganizationClientAccess = apps.get_model('vendors', 'OrganizationClientAccess')
    OrganizationClientAccess.objects.filter(
        organization_unit__parent__isnull=False,
    ).exclude(
        min_cpi__isnull=True,
        max_cpi__isnull=True,
    ).update(inherit_cpi_range=False)


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_organizationclientaccess_max_cpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationclientaccess',
            name='inherit_cpi_range',
            field=models.BooleanField(default=True, help_text="When enabled, a child rule keeps the closest parent rule's CPI range."),
        ),
        migrations.RunPython(preserve_existing_child_cpi_overrides, migrations.RunPython.noop),
    ]
