# Generated by Django 5.2.5 on 2026-08-20 07:32

import django.core.validators
from django.db import migrations, models


def copy_legacy_timing(apps, schema_editor):
    Integration = apps.get_model('vendors', 'ClientIntegration')
    for integration in Integration.objects.only(
        'pk', 'profile_reuse_eligible_after_days', 'profile_rereuse_cooldown_days'
    ).iterator(chunk_size=500):
        Integration.objects.filter(pk=integration.pk).update(
            profile_reuse_first_delay_minutes=max(
                1, int(integration.profile_reuse_eligible_after_days or 60) * 1440
            ),
            profile_reuse_min_interval_minutes=max(
                1, int(integration.profile_rereuse_cooldown_days or 30) * 1440
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0022_organizationclientaccess_inherit_cpi_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientintegration',
            name='profile_reuse_first_delay_minutes',
            field=models.PositiveIntegerField(default=86400, help_text='Minimum age of a newly registered profile before its first reuse, stored in minutes so the policy can be expressed in minutes, hours, or days.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1051200)]),
        ),
        migrations.AddField(
            model_name='clientintegration',
            name='profile_reuse_max_uses_per_window',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum reuses allowed for one UID inside the configured rolling window.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='clientintegration',
            name='profile_reuse_min_interval_minutes',
            field=models.PositiveIntegerField(default=43200, help_text='Minimum time between two reuses of the same UID.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1051200)]),
        ),
        migrations.AddField(
            model_name='clientintegration',
            name='profile_reuse_window_minutes',
            field=models.PositiveIntegerField(default=1440, help_text='Rolling window used by the per-UID reuse limit.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1051200)]),
        ),
        migrations.RunPython(copy_legacy_timing, migrations.RunPython.noop),
    ]
