# Generated by Django 5.2.17 on 2026-08-20 19:23

import uuid
from django.db import migrations, models


def assign_existing_supplier_codes(apps, schema_editor):
    Profile = apps.get_model("vendors", "VendorCommercialProfile")
    for profile in Profile.objects.filter(supplier_code__isnull=True).only("pk"):
        profile.supplier_code = str(500000 + profile.pk)
        profile.save(update_fields=["supplier_code"])


def assign_unique_api_public_ids(apps, schema_editor):
    APIKey = apps.get_model("vendors", "VendorAPIKey")
    for api_key in APIKey.objects.all().only("pk"):
        api_key.public_id = uuid.uuid4()
        api_key.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0023_clientintegration_profile_reuse_first_delay_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapikey',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(assign_unique_api_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vendorapikey',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='vendorclientallocation',
            name='complete_redirect_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='vendorclientallocation',
            name='invalid_redirect_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='vendorclientallocation',
            name='over_quota_redirect_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='vendorclientallocation',
            name='quality_redirect_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='vendorclientallocation',
            name='terminate_redirect_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='vendorcommercialprofile',
            name='callback_hash_enabled',
            field=models.BooleanField(default=False, help_text='Add an HMAC-SHA256 hash to respondent outcome redirects for this supplier.'),
        ),
        migrations.AddField(
            model_name='vendorcommercialprofile',
            name='callback_hash_secret_changed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vendorcommercialprofile',
            name='callback_hash_secret_last_four',
            field=models.CharField(blank=True, editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='vendorcommercialprofile',
            name='encrypted_callback_hash_secret',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='vendorcommercialprofile',
            name='supplier_code',
            field=models.CharField(blank=True, editable=False, help_text='Immutable RM Wins supplier ID shared across every assigned client.', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendorcommercialprofile',
            name='survey_id_mode',
            field=models.CharField(choices=[('project_id', 'RM Wins project ID'), ('source_id', 'Client survey ID')], default='project_id', help_text="Identifier exposed as survey_id in this supplier's API and redirects.", max_length=16),
        ),
        migrations.AddField(
            model_name='vendorsurveyallocation',
            name='is_excluded',
            field=models.BooleanField(db_index=True, default=False, help_text='Hide this project while leaving every other project in the client grant visible.'),
        ),
        migrations.RunPython(assign_existing_supplier_codes, migrations.RunPython.noop),
    ]
