# Generated by Django 5.2.17 on 2026-08-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0024_vendorapikey_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorapikey',
            name='client_allocations',
            field=models.ManyToManyField(blank=True, help_text='Client grants this key may expose. Active project exclusions are applied automatically.', related_name='api_keys', to='vendors.vendorclientallocation'),
        ),
    ]
